/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class dev_matrixlab_webp4j_NativeWebP */

#ifndef _Included_dev_matrixlab_webp4j_NativeWebP
#define _Included_dev_matrixlab_webp4j_NativeWebP
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     dev_matrixlab_webp4j_NativeWebP
 * Method:    getInfo
 * Signature: ([B[I)Z
 */
JNIEXPORT jboolean JNICALL Java_dev_matrixlab_webp4j_NativeWebP_getInfo
  (JNIEnv *, jobject, jbyteArray, jintArray);

/*
 * Class:     dev_matrixlab_webp4j_NativeWebP
 * Method:    getFeatures
 * Signature: ([BILdev/matrixlab/webp4j/WebPBitstreamFeatures;)I
 */
JNIEXPORT jint JNICALL Java_dev_matrixlab_webp4j_NativeWebP_getFeatures
  (JNIEnv *, jobject, jbyteArray, jint, jobject);

/*
 * Class:     dev_matrixlab_webp4j_NativeWebP
 * Method:    encodeRGB
 * Signature: ([BIIIF)[B
 */
JNIEXPORT jbyteArray JNICALL Java_dev_matrixlab_webp4j_NativeWebP_encodeRGB
  (JNIEnv *, jobject, jbyteArray, jint, jint, jint, jfloat);

/*
 * Class:     dev_matrixlab_webp4j_NativeWebP
 * Method:    encodeRGBA
 * Signature: ([BIIIF)[B
 */
JNIEXPORT jbyteArray JNICALL Java_dev_matrixlab_webp4j_NativeWebP_encodeRGBA
  (JNIEnv *, jobject, jbyteArray, jint, jint, jint, jfloat);

/*
 * Class:     dev_matrixlab_webp4j_NativeWebP
 * Method:    encodeLosslessRGB
 * Signature: ([BIII)[B
 */
JNIEXPORT jbyteArray JNICALL Java_dev_matrixlab_webp4j_NativeWebP_encodeLosslessRGB
  (JNIEnv *, jobject, jbyteArray, jint, jint, jint);

/*
 * Class:     dev_matrixlab_webp4j_NativeWebP
 * Method:    encodeLosslessRGBA
 * Signature: ([BIII)[B
 */
JNIEXPORT jbyteArray JNICALL Java_dev_matrixlab_webp4j_NativeWebP_encodeLosslessRGBA
  (JNIEnv *, jobject, jbyteArray, jint, jint, jint);

/*
 * Class:     dev_matrixlab_webp4j_NativeWebP
 * Method:    decodeRGBInto
 * Signature: ([B[BI)Z
 */
JNIEXPORT jboolean JNICALL Java_dev_matrixlab_webp4j_NativeWebP_decodeRGBInto
  (JNIEnv *, jobject, jbyteArray, jbyteArray, jint);

/*
 * Class:     dev_matrixlab_webp4j_NativeWebP
 * Method:    decodeRGBAInto
 * Signature: ([B[BI)Z
 */
JNIEXPORT jboolean JNICALL Java_dev_matrixlab_webp4j_NativeWebP_decodeRGBAInto
  (JNIEnv *, jobject, jbyteArray, jbyteArray, jint);

#ifdef __cplusplus
}
#endif
#endif
