/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class dev_matrixlab_webp4j_WebP4j */

#ifndef _Included_dev_matrixlab_webp4j_WebP4j
#define _Included_dev_matrixlab_webp4j_WebP4j
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     dev_matrixlab_webp4j_WebP4j
 * Method:    encodeRGB
 * Signature: ([BIIIF)[B
 */
JNIEXPORT jbyteArray JNICALL Java_dev_matrixlab_webp4j_WebP4j_encodeRGB
  (JNIEnv *, jobject, jbyteArray, jint, jint, jint, jfloat);

/*
 * Class:     dev_matrixlab_webp4j_WebP4j
 * Method:    encodeRGBA
 * Signature: ([BIIIF)[B
 */
JNIEXPORT jbyteArray JNICALL Java_dev_matrixlab_webp4j_WebP4j_encodeRGBA
  (JNIEnv *, jobject, jbyteArray, jint, jint, jint, jfloat);

#ifdef __cplusplus
}
#endif
#endif
